version: '3.11'

services:
  QueryPilot:
    build: .
    container_name: QueryPilot
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs         # Persist logs
      - ./data:/app/data         # Store vector db files
    stdin_open: true             # For keyboard module
    tty: true
    network_mode: "host"         # Required for GUI/keyboard (esp. on Linux desktop)
    # privileged: true           # Uncomment if needed on Linux for full device access
    command: python src/sql_mcp.py