base:
  project: sql_query_completion
  sleep_time: 0.2
  window_name: 
    - MySQL Workbench
    - pgAdmin 4
data :
  loc : data\raw\sql_text_to_sql.csv
  source: gretelai/synthetic_text_to_sql

llm:
  model_name: meta-llama/llama-4-scout-17b-16e-instruct

triggers:
  initiater: ctrl+c
  filler: tab
  key: \t
  quiting: esc
  remove_ghost:
    c: ctrl
    key: z
  speed_write: 0.01

vector_store:
  type: faiss
  index_path: data/processed/sql_faiss_index.index
  metadata_path: data/processed/sql_metadata.pkl
  top_k: 5
  
  # only for chroma
  persist_directory: data/processed/chroma
  collection_name_chroma: my_chroma_collection

  # only for pinecone
  index_name: my-index
  dimension: 384
  namespace: default
  metric: cosine         # or euclidean, dotproduct
  batch_size: 100

embedding_model: all-MiniLM-L6-v2
