base:
  project: sql_query_completion
  sleep_time: 0.2
  window_name: 
    - MySQL Workbench
    - pgAdmin 4

triggers:
  initiater: ctrl+c
  filler: tab
  key: \t
  quiting: esc
  remove_ghost:
    c: ctrl
    key: z
  speed_write: 0.01