base : 
  project : SQL Query Completion
  sleep_time: 0.2
  window_name: 
    - MySQL Workbench
    - pgAdmin 4
data :
  loc : data\raw\sql_text_to_sql.csv
  source: gretelai/synthetic_text_to_sql

vector_store:
  index_path: data/processed/sql_faiss_index.index
  metadata_path: data/processed/sql_metadata.pkl
  top_k: 3

llm:
  model: meta-llama/llama-4-scout-17b-16e-instruct

triggers:
  initiater: ctrl+c
  filler: tab
  key: \t
  quiting: esc
  remove_ghost:
    c: ctrl
    key: z
  speed_write: 0.01
