name: SQL Copilot CICD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run syntax check
      run: python -m py_compile src/sql_mcp.py

    - name: Vector store connection
      run: |
        python src/retrieve_context.py
        echo "Vector store connected successfully!"